### ISSUE TITLE
Load form URL

### ISSUE THREAD

**Issue by lorencogonzaga** [ElvinJin/Video-Background-GIF#4]
Hi @ElvinJin ElvinJin

Thanx for the code, awesome!

How to change the current code to load the gif from a URL ? From giphy.com something like:

http://media.giphy.com/media/WtNvY4Ao102wE/giphy.gif

Cheers!

**Comment by ElvinJin** [comment]
Hi Lorenco,




Thank you for contacting. For your question, I just think of a way of doing this, I haven’t tried it yet, but it is supposed to work.




Here are the steps:

1. construct a simple html to contain a gif using source with the url you want.

2. in this component, set its size to the screen size of the device.

3. load this html using the web view. 




So whenever you want to change gif, just construct another HTML and reload the web view using the new html text.




It should be working. let me know if you have any better thoughts.




Best Regards,

Elvin


—
