### ISSUE TITLE
is using a webView the optimal solution?

### ISSUE THREAD

**Issue by remzr7** [ElvinJin/Video-Background-GIF#6]
Wouldn't it be better to use AVFoundation?

**Comment by ElvinJin** [comment]
Yes it is.

**Comment by remzr7** [comment]
AVFoundation however has a lag when looping though. Does WebView have the same issue?

**Comment by ElvinJin** [comment]
In the view that I created I didn't see any obvious lag so I guess it's not
problem. Also, my friend did this using AVFoundation it also has good
quality without lag. Maybe it is related to the video quality/file size,
etc? But to be honest, GIF solution takes too much space if you wanna have
good color on your video.

On Wed, Mar 18, 2015 at 12:34 AM, Rameez Remsudeen <notifications@github.com
> wrote:

> AVFoundation however has a lag when looping though. Does WebView have the
> same issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ElvinJin/Video-Background-GIF/issues/6#issuecomment-82455632>
> .
>



-- 
Elvin Jin
Computer Science | The Chinese University of Hong Kong
(+852) 6686-5120 | elvinjin8@gmail.com
